### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nanosonde** [dersimn/mqtt-smarthome-webui#1]
Hi!

Do you have "bigger" plans for this or is this something that is just meant for your own use? ;)

I like the simplicity of the internals.

**Comment by dersimn** [comment]
Yeah.. I've no interest in building "yet another _greatest_ web interface" that turn's out to be a bit shitty anyways.

I'll implement a few more controls, maybe a log view but that's it.
If you have more ambitions - feel free to fork ;) I'll probably grab a bit of your KNX stuff for my next project.

**Comment by nanosonde** [comment]
Ok, thanks for the open words. ;)
